[package]
name = "xyo-sdk"
description = "XYO Financial Official SDK for Rust"
version = "0.1.0"
edition = "2021"
authors = [
    "Hadi Tajallaei <hadi@syniol.com"
]
license = "Apache-2.0"
license-file = "LICENSE"

[dependencies]
http-request = "8.91.14"

